name: pokemmo
title: PokeMMO
base: core24
version: '3.0a'
summary: PokeMMO Game Client
license: 'Proprietary'
grade: stable
confinement: strict
compression: lzo
description: |
  PokeMMO is an online-only emulator for several popular Nintendo DS & Game Boy Advance games,
  allowing you to play, talk, fight, and trade with other players in realtime across multiple
  platforms.

  This game requires a constant internet connection. Usage of this program requires an account
  with https://pokemmo.com/ and requires you to accept the PokeMMO Terms of Service at login

platforms:
  amd64:
    build-on: amd64
    build-for: amd64
  arm64:
    build-on: arm64
    build-for: arm64

assumes:
  - snapd2.55.5

package-repositories:
  - type: apt
    components: [ main ]
    suites: [ stable ]
    key-id: 99A5C88E3C5B1FA8B05A19D332E9750179FCEA62
    url: https://apt.bell-sw.com/

apps:
  pokemmo:
    command: runtime/bin/java -jar $SNAP/jar/unix-installer.jar
    extensions: [ gnome ]
    plugs:
      - network
      - opengl
      - home
      - joystick
      - audio-playback
      - removable-media
    environment:
      JAVA_HOME: "$SNAP/runtime"
      PATH: "$JAVA_HOME/bin/:$PATH"
      _JAVA_OPTIONS: '-Dfile.encoding="UTF-8"'
      XDG_DATA_HOME: "$SNAP/usr/share"
      XDG_CONFIG_HOME: "$XDG_DATA_HOME/.config"
      POKEMMO_IS_SNAPPED: '1'
      LIBDECOR_PLUGIN_DIR: $SNAP/usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/libdecor/plugins-1

parts:
  gradle:
    plugin: nil
    override-pull: |
      curl --connect-timeout 5 --retry 5 -L https://services.gradle.org/distributions/gradle-8.14.3-bin.zip -o gradle-8.14.3-bin.zip
      mv gradle-8.14.3-bin.zip $CRAFT_STAGE/
    build-packages:
      - curl
  pokemmo:
    after: [ gradle ]
    plugin: dump
    source: https://github.com/kyu-n/pokemmo-unix-installer.git
    source-type: git
    build-environment:
      - GRADLE_USER_HOME: "$CRAFT_PART_BUILD/.gradle"
      # These proxy settings ensure Gradle can download dependencies while running on snapcraft.io
      - GRADLE_OPTS: "-Djava.net.useSystemProxies=true -Dfile.encoding=UTF-8"
      - JAVA_OPTS: "-Djava.net.useSystemProxies=true"
    override-pull: |
      craftctl default
      cp $CRAFT_STAGE/gradle-8.14.3-bin.zip $CRAFT_PART_SRC/gradle/wrapper/gradle-8.14.3-bin.zip
    override-build: |
      set -ex
      
      # Libdecor directory structure required
      mkdir -p $SNAPCRAFT_PART_INSTALL/usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/libdecor/plugins-1/
      
      # Set JRE target based on architecture
      case "$CRAFT_ARCH_BUILD_FOR" in
        amd64) export JRE_TARGET="/usr/lib/jvm/bellsoft-java21-amd64" ;;
        arm64) export JRE_TARGET="/usr/lib/jvm/bellsoft-java21-aarch64" ;;
      esac
      
      # Set Java home for the build
      export JAVA_HOME="${JRE_TARGET}"
      
      ./gradlew assemble --no-daemon --stacktrace
      
      # Install built artifacts
      mkdir -p $CRAFT_PART_INSTALL/jar
      cp build/libs/unix-installer.jar $CRAFT_PART_INSTALL/jar/unix-installer.jar
      mv build/runtime $CRAFT_PART_INSTALL/
    stage-packages:
      - libglu1-mesa
      - zenity
      - libdecor-0-0
      - libdecor-0-plugin-1-gtk
    build-packages:
      - bellsoft-java21
      - ca-certificates-java