name: pokemmo
title: PokeMMO
base: core24
version: '3.0c'
summary: PokeMMO Game Client
license: 'Proprietary'
grade: stable
confinement: strict
compression: lzo
description: |
  PokeMMO is an online-only emulator for several popular Nintendo DS & Game Boy Advance games,
  allowing you to play, talk, fight, and trade with other players in realtime across multiple
  platforms.

  This game requires a constant internet connection. Usage of this program requires an account
  with https://pokemmo.com/ and requires you to accept the PokeMMO Terms of Service at login

platforms:
  amd64:
    build-on: amd64
    build-for: amd64
  arm64:
    build-on: arm64
    build-for: arm64

assumes:
  - snapd2.55.5

package-repositories:
  - type: apt
    components: [ main ]
    suites: [ stable ]
    key-id: 99A5C88E3C5B1FA8B05A19D332E9750179FCEA62
    url: https://apt.bell-sw.com/

apps:
  pokemmo:
    command: runtime/bin/java -jar $SNAP/jar/unix-installer.jar
    extensions: [ gnome ]
    plugs:
      - network
      - opengl
      - home
      - joystick
      - audio-playback
      - removable-media
    environment:
      JAVA_HOME: "$SNAP/runtime"
      PATH: "$JAVA_HOME/bin/:$PATH"
      _JAVA_OPTIONS: '-Dfile.encoding="UTF-8"'
      XDG_DATA_HOME: "$SNAP/usr/share"
      XDG_CONFIG_HOME: "$XDG_DATA_HOME/.config"
      POKEMMO_IS_SNAPPED: '1'
      LIBDECOR_PLUGIN_DIR: $SNAP/usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/libdecor/plugins-1

parts:
  pokemmo:
    plugin: dump
    source: https://github.com/kyu-n/pokemmo-unix-installer/releases/download/v3.0a-stable/v3.0a-stable.zip
    source-type: zip
    override-build: |
      # The JAR is already extracted by the dump plugin
      mkdir -p $CRAFT_PART_INSTALL/jar
      cp unix-installer.jar $CRAFT_PART_INSTALL/jar/
      
      # Handle runtime directory
      mkdir -p $CRAFT_PART_INSTALL/runtime
      cp -r /usr/lib/jvm/bellsoft-java21-*/* $CRAFT_PART_INSTALL/runtime/ || true
    stage-packages:
      - bellsoft-java21-runtime
      - libglu1-mesa
      - zenity
      - libdecor-0-0
      - libdecor-0-plugin-1-gtk
    build-packages:
      - bellsoft-java21
      - ca-certificates-java