name: Java CI with Gradle

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
env:
  GRADLE_USER_HOME: .gradle

jobs:
  buildjar:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.2.2
      - uses: actions/cache@v4.1.2
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          java-package: jdk
          architecture: x64
          distribution: 'liberica'
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4
        with:
          gradle-version: "8.10.2"
      - name: Build with Gradle
        run: gradle jar
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          path: |
            build/distribution/unix-installer.jar